services:
  batch-go:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: builder
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    tty: true
    environment:
      - TZ=Asia/Tokyo